@startuml

actor Client
rectangle "Authentication System" {
    usecase Authenticate
}

rectangle System {
    usecase ViewAllPhones
    usecase ViewAllUsers
    usecase CreateNewUser
    usecase DeleteUser
    usecase ViewAsinglePhone
}

Client --> Authenticate
Authenticate --> (ViewAllPhones)
Authenticate --> (ViewAsinglePhone)
Authenticate --> (ViewAllUsers)
Authenticate --> (CreateNewUser)
Authenticate --> (DeleteUser)

@enduml
