@startuml

class Client {
  - id
  - name
  - description
  - users: Collection<User>
  + getId()
  + getName()
  + setName(name)
  + getDescription()
  + setDescription(desc)
  + getUsers()
  + addUser(user)
  + removeUser(user)
}

class Phone {
  - id
  - brand
  - modelName
  - description
  - memoryStorage
  - screenSize
  - wirelessNetwork
  + getId()
  + getBrand()
  + setBrand(brand)
  + getModelName()
  + setModelName(name)
  + getDescription()
  + setDescription(desc)
  + getMemoryStorage()
  + setMemoryStorage(storage)
  + getScreenSize()
  + setScreenSize(size)
  + getWirelessNetwork()
  + setWirelessNetwork(network)
}

class User {
  - id
  - email
  - roles
  - password
  - firstName
  - lastName
  - address
  - siren
  - mobile
  - client: Client
  + getId()
  + getEmail()
  + setEmail(email)
  + getUserIdentifier()
  + getUsername()
  + getRoles()
  + setRoles(roles)
  + getPassword()
  + setPassword(password)
  + eraseCredentials()
  + getFirstName()
  + setFirstName(firstName)
  + getLastName()
  + setLastName(lastName)
  + getAddress()
  + setAddress(address)
  + getSiren()
  + setSiren(siren)
  + getMobile()
  + setMobile(mobile)
  + getClient()
  + setClient(client)
}

Client  "1" -- "n" User

@enduml
